// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHA-9ars93fBo2DCz6AvLqsxHhAVv9uA',
    appId: '1:385617781408:web:5817dbefca80f759781fc5',
    messagingSenderId: '385617781408',
    projectId: 'passwordsaver-b9dda',
    authDomain: 'passwordsaver-b9dda.firebaseapp.com',
    storageBucket: 'passwordsaver-b9dda.appspot.com',
    measurementId: 'G-28LLFX8R64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNKrex9Yv2ZZtOrdrtIMrhhJwe43tzdE',
    appId: '1:385617781408:android:522ecc42f865136f781fc5',
    messagingSenderId: '385617781408',
    projectId: 'passwordsaver-b9dda',
    storageBucket: 'passwordsaver-b9dda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16sl13BBnfLzt-sxRxXd5y_9FaXJNyWU',
    appId: '1:385617781408:ios:24417445deae7a7d781fc5',
    messagingSenderId: '385617781408',
    projectId: 'passwordsaver-b9dda',
    storageBucket: 'passwordsaver-b9dda.appspot.com',
    iosClientId: '385617781408-l9svqgavvt2epb6bhqv1gq8j3kpgnvvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordsaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB16sl13BBnfLzt-sxRxXd5y_9FaXJNyWU',
    appId: '1:385617781408:ios:24417445deae7a7d781fc5',
    messagingSenderId: '385617781408',
    projectId: 'passwordsaver-b9dda',
    storageBucket: 'passwordsaver-b9dda.appspot.com',
    iosClientId: '385617781408-l9svqgavvt2epb6bhqv1gq8j3kpgnvvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordsaver',
  );
}
